openapi: 3.2.0
info:
  title: Converis Web Services Configuration - Entity definitions API
  description: This API Specification describes how to read data from Converis in order to use it in other systems.
  contact:
    email: converis-info@clarivate.com
  version: '2.0'
servers:
- url: https://api.clarivate.com/converisreadapi
tags:
- name: Configuration - Entity definitions
  description: Get the configured entity definitions
paths:
  /config/entities:
    get:
      tags:
      - Configuration - Entity definitions
      summary: Get definition of all entities
      description: 'Get definition of all entities. Additionally, you can


        * specify language of labels through the query parameter ___language___

        * include (excluded by default) linkentity reference API path through HTTP header ___Converis-linkentity-references___. The information about link entities can be requested through the responded paths.

        * include (excluded by default) all attributes definitions of the entity through HTTP Header ___Converis-attribute-definition___'
      parameters:
      - name: startRecord
        in: query
        description: Starting record.
        required: false
        style: form
        explode: true
        schema:
          minimum: 1
          type: integer
          format: int32
          default: 1
      - name: count
        in: query
        description: Number of records to return.
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 1
          type: integer
          format: int32
          default: 10
      - name: language
        in: query
        description: Return only labels or data for specific language. Display all configured languages if null, eg. en_GB
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: en_GB
      - name: Converis-linkentity-references
        in: header
        description: Set true if link entity references (href) should be returned.
        required: false
        style: simple
        explode: false
        schema:
          type: boolean
          default: false
      - name: Converis-attribute-definition
        in: header
        description: Choose ALL to display all attributes
        required: false
        style: simple
        explode: false
        schema:
          type: string
          default: NONE
          enum:
          - NONE
          - ALL
      responses:
        '200':
          description: Successfull response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityDefinitionList'
        default:
          description: Error response 400+
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
      security:
      - BasicAuth: []
      operationId: getConfigEntities
      x-operation-id-source: derived
  /config/entities/{type}:
    get:
      tags:
      - Configuration - Entity definitions
      summary: Get definition of an entity
      description: 'Get definition of an entities by ___type___ name. Additionally, you can


        * specify language of labels through the query parameter ___language___

        * include (excluded by default) linkentity reference API path through HTTP header ___Converis-linkentity-references___. The information about link entities can be requested through the responded paths.

        * include (excluded by default) specific or all attributes definitions of the entity through HTTP Header ___Converis-attribute-definition___'
      parameters:
      - name: type
        in: path
        description: entity type name
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: language
        in: query
        description: Return only labels or data for specific language. Display all configured languages if null, eg. en_GB
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Converis-linkentity-references
        in: header
        description: Set true if link entity references (href) should be returned.
        required: false
        style: simple
        explode: false
        schema:
          type: boolean
          example: false
          default: false
      - name: Converis-attribute-definition
        in: header
        description: Choose ALL to display all attributes
        required: false
        style: simple
        explode: false
        schema:
          type: string
          default: NONE
          enum:
          - NONE
          - ALL
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EntityDefinition'
        default:
          description: Error response 400+
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultResponse'
      security:
      - BasicAuth: []
      operationId: getConfigEntitiesByType
      x-operation-id-source: derived
components:
  schemas:
    WorkflowStep:
      required:
      - label
      - stepNr
      properties:
        stepNr:
          type: integer
          example: 2
        label:
          type: array
          example:
          - language: en_GB
            value: Validated
          - language: de_DE
            value: Validiert
          items:
            $ref: '#/components/schemas/LabelDefinition'
    EntityDefinition:
      required:
      - description
      - dynamicTypeSelector
      - id
      - isVersionableFile
      - linkEntityReferences
      - name
      - plural
      - singular
      - workflowSteps
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1231421421
        name:
          type: string
          example: Publication
        isVersionableFile:
          type: boolean
          example: true
        description:
          type: string
        maximumStatusStep:
          type: integer
          example: 4
        dynamicTypeSelector:
          type: string
          example: Publication Type
        singular:
          type: array
          example:
          - language: en_US
            value: Publication
          - language: de_DE
            value: Publikation
          items:
            $ref: '#/components/schemas/LabelDefinition'
        plural:
          type: array
          example:
          - language: en_US
            value: Publications
          - language: de_DE
            value: Publikationen
          items:
            $ref: '#/components/schemas/LabelDefinition'
        workflowSteps:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowStep'
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeDefinition'
        links:
          type: array
          example:
          - rel: PUBL_has_CARD
            href: /converis-api/ws/v2/config/linkentities/PUBL_has_CARD
          - rel: PUBL_has_ORGA
            href: /converis-api/ws/v2/config/linkentities/PUBL_has_ORGA
          items:
            $ref: '#/components/schemas/LinkReference'
    LabelDefinition:
      required:
      - language
      - value
      type: object
      properties:
        language:
          type: string
          description: The system language abbreviation
          example: en_US
        value:
          type: string
          description: The value of the label
          example: Publication
    AttributeDefinition:
      required:
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 16287
        name:
          type: string
          example: acceptanceDate
        dataInput:
          $ref: '#/components/schemas/AttributeInputDefinition'
        multilanguage:
          type: boolean
          example: false
        description:
          type: string
          example: 'The date when the author received notice that the submitted proposal got accepted and following that he can submit a paper

            '
        labels:
          type: array
          example:
          - language: en_US
            value: Acceptance date
          - language: de_DE
            value: Datum
          items:
            $ref: '#/components/schemas/LabelDefinition'
        mandatory:
          type: boolean
          example: false
        allowPublicSearch:
          type: boolean
          example: true
        internallySearcheable:
          type: boolean
          example: true
        includeInPageExport:
          type: boolean
          example: true
    AttributeInputDefinition:
      properties:
        dataType:
          type: string
          example: DATE
        renderingTypeHint:
          type: string
          example: Datepicker
        inputPattern:
          type: string
          example: Date
        defaultExpression:
          type: string
          example: 01-05-2019
    EntityDefinitionList:
      required:
      - count
      - data
      - nrRecordsAll
      - nrRecordsFound
      - startRecord
      type: object
      properties:
        startRecord:
          type: integer
          example: 1
        count:
          type: integer
          example: 50
        nrRecordsAll:
          type: integer
          example: 1540
        nrRecordsFound:
          type: integer
          example: 50
        data:
          type: array
          items:
            $ref: '#/components/schemas/EntityDefinition'
    DefaultResponse:
      required:
      - statusDescirption
      - message
      - path
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
          description: The date-time notation as defined by RFC 3339, section 5.6, e.g. "2017-07-21T17:32:28Z"
          format: date-time
        path:
          type: string
          description: The path which is used by user, e.g./converis-apis/ws/v2/data/entities/Publication
          format: uri
        status:
          type: integer
          description: HTTP Status code,e.g. 400+
          example: 400
        statusDescription:
          type: string
          description: Description of HTTP Status code, e.g. Bad Request
          example: Bad Request
        message:
          type: string
          description: The detailed description of the error
    LinkReference:
      required:
      - rel
      - href
      type: object
      properties:
        rel:
          type: string
          description: Describes the type of relationship.
          example: Publication
        href:
          type: string
          description: is the complete endpoint path that uniquely defines the resource.
          example: /converis-apis/ws/v2/data/Publication/linked/PUBL_has_JOUR/1234
  securitySchemes:
    BasicAuth:
      type: http
      description: The authentication information has to be provided by the client application as Basic authentication header. This can be configured by an admin in Converis under Configuration -> API Authentication Info.
      scheme: basic
